### ISSUE TITLE
安全漏洞

### ISSUE THREAD

**Issue by vivisidea** [six-ddc/v2ex-shell-client#2]
有个严重的安全漏洞，没对显示的数据进行escape，比如我这里输入

```
`echo "WARNING"`
```

然后你看命令是不是被执行了。。。。

```
printf "%3dL. $pink$member$reset $cyan$content$reset $created\n" "$(($i+1))"

-- 测试
vivi@ssd:/tmp/v2ex-shell-client$ printf "%3dL `echo "WARNING"`\n" 3
  3L WARNING
```

**Comment by six-ddc** [comment]
谢谢反馈。其实经测试并不会出现该问题，因为从api获取的字符串已经是普通的文本，并没有被解释执行的过程，这里使用以下进行简单测试：
➜  v2ex-shell-client git:(master) ✗ cat a.txt
{
    "name" : "`ls`"
}
➜  v2ex-shell-client git:(master) ✗ var=`cat a.txt | jq -r ".name"`
➜  v2ex-shell-client git:(master) ✗ echo "===$var===" $var
===`ls`=== `ls`
针对你上面的情况其实是在""中对`echo "WARNING"`进行了解释，但是如果文本本身就是`echo "WARNING"`则不会有问题，如以下测试：
➜  v2ex-shell-client git:(master) ✗ xx='`echo "WARNING"`'
➜  v2ex-shell-client git:(master) ✗ echo "===$xx==="
===`echo "WARNING"`===
这里其实是双引号和单引号的区别，双引号内的内容会被解释执行，而单引号的文本本身则不会。
